(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"gatewise_300x100_v3_atlas_1", frames: [[0,162,64,64],[0,0,160,160]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Image = function() {
	this.initialize(ss["gatewise_300x100_v3_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.image25 = function() {
	this.initialize(ss["gatewise_300x100_v3_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol58 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFzCQQgkglAAg2QAAg2AkglQAkgjA2gBQA2ABAjAjQAlAlAAA2QAAA2glAlQgjAkg2AAQg2AAgkgkgAGiACQgSASAAAhQAAAgASASQARASAaAAQAZAAARgRQATgTAAggQAAghgTgSQgRgQgZAAQgaAAgRAQgAojCQQgkglAAg2QAAg2AkglQAjgjA2gBQA2ABAkAjQAkAlAAA2QAAA2gkAlQgkAkg2AAQg2AAgjgkgAn0ACQgSASAAAhQAAAgASASQARASAZAAQAaAAARgRQASgTAAggQAAghgSgSQgRgQgaAAQgZAAgRAQgAsnCQQglglAAg2QAAg2AkglQAjgjA1gBQAuABAfAZQAbAWAJAgIg6AUQgFgRgMgKQgOgMgWAAQgaAAgRAQQgSATAAAfQAAAfASATQARARAaABQAXAAAPgOQAMgKAFgRIA5ATQgJAhgbAXQgfAZgtAAQg1AAgkgkgAMBCjQgNgNAAgTQAAgRANgOQANgNASAAQATAAANANQANAOAAARQAAATgNANQgNANgTAAQgSAAgNgNgAAdCdQgUgVAAgiIAAhvIgrAAIAAg6IANAAQASAAAJgKQAJgKAAgRIAAgiIA6AAIAABHIAxAAIAAA6IgxAAIAABkQAAAPAHAHQAHAFAPABQANAAAHgCIAAA1QgQAGgVAAQgjAAgVgTgAJ5CtIAAlgIBAAAIAAFggACoCtIAAjwIA/AAIAAAkQASglAzAAIAOABIAABBQgJgBgKgBQg+ABAABCIAABugAiECtIAAiMQAAgWgKgLQgLgOgXAAQgUAAgNAOQgMANAAAWIAACKIhBAAIAAjwIBAAAIAAAeQAKgRAUgKQASgIAVgBQAqAAAXAcQAVAaAAApIAACXg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol58, new cjs.Rectangle(-84.5,-18,169.1,36), null);


(lib.Symbol57 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIsBlQgVgVgDgbIA3gMQABAQALAKQAMALAUAAQAQAAAIgIQAIgGAAgKQAAgSgagGIgfgHQgigHgSgTQgQgTAAgaQAAggAZgXQAagXAmAAQAvAAAZAZQAUASADAaIg2AMQgCgNgIgIQgLgLgTAAQgNAAgIAHQgJAHAAAKQAAARAVAEIAjAIQAiAHATATQASATAAAbQAAAggYAWQgZAZgsAAQgwAAgcgagAFQBlQgVgVgDgbIA3gMQABAQAMAKQAMALATAAQAPAAAKgIQAHgGAAgKQAAgSgZgGIghgHQghgHgRgTQgRgTABgaQgBggAagXQAZgXAnAAQAuAAAaAZQATASADAaIg2AMQgCgNgIgIQgLgLgSAAQgNAAgKAHQgIAHAAAKQAAARAWAEIAiAIQAjAHASATQASATAAAbQAAAggXAWQgaAZgsAAQgxAAgbgagABXBeQglglgBg5QAAg4AlgkQAigiAvAAQA4AAAgAhQAgAhgBA6IgBATIisAAQACAYARAPQASAQAYAAQAqAAANglIA2AQQgJAhgcAVQgeAWgqAAQg0AAgjghgACCg6QgOANgBATIBrAAQAAgUgMgNQgPgOgaAAQgYAAgPAPgAiuBbQgkgkAAg3QAAg2AkgkQAkgkA1AAQAtAAAfAZQAaAWAJAiIg5ATQgFgRgMgLQgOgMgWAAQgaAAgRARQgSATAAAeQAAAfASAUQARARAaAAQAXAAAPgOQANgKAEgRIA5ATQgJAigaAWQggAZgtAAQg1AAglgkgAmyBbQglgkAAg3QAAg2AkgkQAkgkA1AAQAuAAAfAZQAbAWAIAiIg6ATQgEgRgNgLQgOgMgWAAQgaAAgRARQgSATAAAeQAAAfASAUQASARAZAAQAXAAAQgOQAMgKAFgRIA5ATQgKAigaAWQggAZgtAAQg1AAgkgkgAq/BpQgVgVAAgeQAAgeAVgUQATgQAggFIA6gJQATgCgBgPQAAgNgKgJQgKgJgUAAQgUAAgNALQgLALgCARIg5gMQADggAagWQAcgZAuAAQA1AAAcAbQAXAYAAAoIAAB1QAAAXADAPIg8AAQgCgMAAgRQgXAkgwAAQglAAgYgWgAp2AVQgdAEAAAaQAAALAHAIQAJAIAPAAQAXAAAOgLQAPgOAAgeIAAgLg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol57, new cjs.Rectangle(-72.5,-12.7,145,25.5), null);


(lib.Symbol56 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFkCTQgkglAAg2QAAg4AkgiQAkgkA2AAQA2AAAjAkQAkAiAAA4QAAA2gkAlQgjAkg2AAQg2AAgkgkgAGTAFQgSASAAAhQAAAgASASQARASAaAAQAZAAARgRQATgTAAggQAAghgTgSQgRgRgZAAQgaAAgRARgAg4CSQghgkAAg2QAAg2AggiQAhglAxAAQAcAAATAKQAPAIAGALIAAiIIBAAAIAAE0QAAAcACAPIg+AAQgDgLAAgQQgIAPgRAJQgTAKgXAAQgyAAghgkgAgGAFQgRATAAAgQAAAfARASQAPATAagBQAZABARgTQARgTAAgfQAAgggRgSQgRgQgZAAQgaAAgPAQgAJ2CvIAAi2IgoAAIAAg5IAoAAIAAgbQAAgpAXgXQAYgZAoAAQAWAAAKAFIAAA2QgHgBgNAAQgOAAgJAGQgLAIAAASIAAAaIA2AAIAAA5Ig2AAIAAC2gAjFCvIAAiMQAAgUgKgNQgLgNgXAAQgVAAgMAOQgMANAAAWIAACJIhBAAIAAjvIA/AAIAAAfQALgSATgKQATgJAVABQAqAAAXAcQAVAZAAAoIAACXgAngCvIAAjvIBBAAIAADvgApQCvIhAhbIgbAdIAAA+IhBAAIAAlfIBBAAIAADJIBThZIBVAAIhgBlIBiCKgAnchyQgMgMAAgPQAAgSAMgMQAMgLAQAAQARAAALALQAMAMAAASQAAAPgMAMQgLAMgRAAQgQAAgMgMg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol56, new cjs.Rectangle(-74.8,-18.3,149.7,36.6), null);


(lib.Symbol55 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGjCUQglgkAAg6QAAg3AkgkQAjgjAvAAQA4AAAfAhQAgAigBA4IgBAUIisAAQACAYARAQQASAPAYAAQApAAAOgkIA2AQQgJAhgcAUQgeAXgqAAQg0AAgjgigAHPgEQgOANgCASIBrAAQAAgUgMgMQgPgOgaAAQgYAAgOAPgAsvCRQgkgkAAg3QAAg2AkgkQAkgkA2AAQA1AAAlAkQAjAkABA2QgBA3gjAkQglAlg1AAQg2AAgkglgAsAAEQgSASgBAgQABAhASASQARASAaAAQAZAAARgRQASgTABghQgBgggSgSQgRgRgZAAQgaAAgRARgAj1CfQgWgVABgdQAAgfAUgTQATgSAggEIA7gJQASgDAAgOQAAgNgKgIQgLgJgTAAQgVAAgNALQgLAKgBAQIg6gMQADgeAagWQAdgaAtAAQA1AAAcAcQAXAYAAAmIAAB2QAAAYAEAOIg8AAQgDgMAAgRQgWAkgwAAQgmAAgXgWgAisBLQgeAFAAAZQAAAMAIAHQAJAJAOAAQAXAAANgMQARgOAAgdIAAgLgAN2CuIg4ijIg3CjIhDAAIhMjvIBEAAIAtCZIA0iZIBFAAIAyCaIAtiaIBAAAIhLDvgAESCuIAAiMQAAgVgKgMQgMgNgWAAQgVAAgMANQgMAOAAAWIAACJIhBAAIAAjvIBAAAIAAAeQAKgRATgKQATgJAVAAQAqAAAXAcQAVAZAAApIAACXgAopCuIAAjvIA/AAIAAAkQAJgVAWgJQARgHAUAAIAPAAIAABCQgJgCgLAAQg+AAAABDIAABtgAvZCuIAAi3IgnAAIAAg4IAnAAIAAgbQAAgpAYgXQAYgZAoAAQAWAAAKAFIAAA2QgJgCgMAAQgOAAgHAHQgMAIAAASIAAAaIA2AAIAAA4Ig2AAIAAC3g");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol55, new cjs.Rectangle(-102.5,-18.1,205.1,36.3), null);


(lib.Symbol54 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEjCVQglgkAAg6QAAg3AlgkQAhgjAwABQA4AAAfAgQAfAiAAA4IAAAVIisAAQABAXASAQQARAQAZAAQApAAANglIA2AQQgKAhgbAUQgeAXgqAAQg0AAgjgigAFPgDQgOANgBATIBrAAQgCgVgMgMQgOgOgaAAQgXAAgPAPgAmqCfQgUgUAAgiIAAhuIgsAAIAAg7IAMAAQATAAAKgLQAJgKAAgRIAAghIA6AAIAABHIAxAAIAAA7IgxAAIAABjQAAAPAIAGQAGAHAOgBQAOAAAHgBIAAA2QgQAFgVAAQgjAAgVgUgACUCvIAAiOQABgVgKgLQgMgMgVAAQgUAAgMANQgMAOAAATIAACMIhAAAIAAiOQABgVgLgLQgLgMgVAAQgVAAgMANQgMANAAAUIAACMIhBAAIAAjvIA+AAIAAAeQAKgRAVgKQASgJAVAAQAYAAATALQASAKAKATQAagoAxAAQAlAAAXAVQAbAZAAAsIAACbgAkbCvIAAjvIBAAAIAADvgAkYhyQgLgMAAgPQAAgSALgMQANgLAQAAQARAAAMALQALAMAAASQAAAPgLAMQgMAMgRAAQgQAAgNgMg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol54, new cjs.Rectangle(-49,-18.3,98.1,36.6), null);


(lib.Symbol53 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AByCXQgVgUgDgbIA3gMQACAQAKAKQAMAKAUAAQAPAAAJgHQAIgGAAgLQAAgSgagFIgfgHQgigHgSgUQgQgTAAgaQAAggAagWQAZgYAnAAQAtAAAbAaQATASADAaIg2ALQgCgMgIgIQgLgLgTAAQgNAAgJAHQgIAGAAALQAAAQAVAEIAjAHQAiAIATATQASAUAAAbQAAAggXAWQgaAZgsAAQgxAAgbgbgAhsCbQgUgUAAgjIAAhvIgsAAIAAg5IAMAAQATgBAJgKQAJgKAAgRIAAgiIA7AAIAABIIAwAAIAAA5IgwAAIAABjQAAAQAHAHQAHAFAOAAQAOAAAGgCIAAA2QgPAGgWAAQgiAAgVgTgAkaCqIAAlYIBFAAIAAFYgAAPhDQAPgDAMgLQAMgMABgRQgDADgHABQgRAAgJgLQgKgJAAgQQAAgPALgKQALgKARAAQATAAAMANQALAOAAAUQAAAsgaAaQgVATgcADg");
	this.shape.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol53, new cjs.Rectangle(-28.3,-17.8,56.6,35.6), null);


(lib.Symbol52 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#811547").s().p("Ao5EJIAAoRIRzAAIAAIRg");
	this.shape.setTransform(-0.0016,-0.0008,0.8705,0.8705);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol52, new cjs.Rectangle(-49.6,-23,99.2,46.1), null);


(lib.Symbol51 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AW0GGQgPgGgIgHQgKgJgFgIIAVgPIAKAKQAFAHAKAEQAKAFAPAAQAWAAANgKQAOgLAAgVIAAgkIgCAAIgJAMQgFAHgKAFQgKAGgRAAQgVAAgRgKQgRgKgKgTQgJgVAAgaQAAgbAJgTQAKgVAQgKQARgLAWAAQARAAAKAFQALAGAFAHIAIAMIADAAIAAgcIAaAAIAACzQAAAXgKAOQgKAOgSAHQgRAHgVAAQgSAAgPgFgAW4C1QgMAKgFAOQgFANAAATQAAARAFAPQAHAPAKAHQALAIASAAQAQAAALgIQALgHAGgOQAGgOAAgTQAAgTgGgOQgFgOgMgJQgLgIgQAAQgRAAgMAIgAi2GGIgHgCIAHgYQAKADAHgBQAIgBAFgGQAHgGAEgNIAFgOIhAivIAdAAIAwCLIACAAIAwiLIAdAAIhKDIQgFANgHAJQgIAJgKAFQgIAEgNAAIgNgBgAZnFDQgMgFgJgNQgIgLAAgSQAAgPAGgJQAGgKAKgFQAJgFAMgDIAygHQALgCAEgCQAFgDAAgGIAAgBQAAgRgKgJQgJgKgSAAQgTAAgLAJQgLAIgFAKIgZgJQAGgQAMgJQAMgJANgEQANgDAOAAQAJAAAKACQANACAIAGQAKAFAIANQAGANAAAUIAABzIgaAAIAAgXIgCAAQgCAFgHAHQgIAHgJAEQgKAFgQAAQgRAAgNgHgAazDyIgnAGQgKABgJADQgKADgFAGQgFAGAAAKQAAAOAKAHQAKAHAQAAQAQAAALgGQALgGAGgKQAGgJAAgMIAAgYIgIAEgAHYFDQgMgFgJgNQgIgNAAgQQAAgPAGgJQAGgKAKgFQAJgFAMgDIAygHQALgCAEgCQAFgCAAgHIAAgBQAAgRgKgJQgJgKgSAAQgTAAgLAJQgLAIgFAKIgZgJQAGgPAMgKQALgJAOgEQANgDAOAAQAJAAAKACQAMACAJAGQALAGAHAMQAGANAAAUIAABzIgaAAIAAgXIgCAAQgCAFgHAHQgIAHgJAEQgKAFgQAAQgRAAgNgHgAIkDyIgnAGQgKABgJADQgKADgFAGQgFAHAAAJQAAAPAKAGQAKAHARAAQAQAAAKgGQALgGAGgKQAGgJAAgMIAAgYQgBABgHADgAeWE+QgSgMgKgTQgKgVAAgaQAAgbAKgVQAKgUASgMQASgLAXAAQAOAAANAEQANAFALAKQALAKAHARQAGASAAAXIAAALIh/AAQABASAGAMQAHAOAMAHQANAHAQAAQALAAAIgDQAJgDAGgGQAHgHACgIIAaAHQgEAOgJAJQgKAKgOAGQgPAFgRAAQgZAAgTgLgAejC1QgLAHgGANQgGALgBAMIBkAAQAAgPgGgLQgGgMgLgHQgLgGgOAAQgQAAgMAIgASYE+QgSgMgKgTQgJgUAAgbQAAgcAJgUQAKgUASgMQASgLAXAAQAOAAANAEQAOAFAKAKQALAKAHARQAGAQAAAZIAAALIh/AAQABASAGAMQAHAOAMAHQANAHAQAAQAKAAAJgDQAJgDAGgGQAGgGAEgJIAZAHQgEAOgJAJQgKAKgOAGQgPAFgRAAQgZAAgTgLgASlC1QgLAHgGANQgGALgBAMIBkAAQAAgOgGgMQgGgMgLgHQgLgGgOAAQgQAAgMAIgAAOE+QgQgLgLgVQgKgTAAgcQAAgcAKgTQAKgVARgLQARgLAYAAQAYAAASALQASAMAJAUQAKAVAAAaQAAAagKAVQgJAUgSAMQgTALgXAAQgXAAgSgLgAAaC2QgMAJgGAQQgFAPAAARQAAARAFAQQAGAPAMAJQAMAJARAAQARAAANgJQAMgKAFgOQAFgOAAgTQAAgSgFgOQgFgPgMgKQgMgJgSAAQgSAAgLAJgAcrFDQgLgFgHgKQgHgJAAgQIAAhtIgaAAIAAgXIAaAAIAAgqIAbAAIAAAqIAlAAIAAAXIglAAIAABlQAAALADAHQAEAFAFACIALACIAHgBIAFgBIAFAZIgHACIgNABQgMAAgKgFgANqFDQgLgFgGgKQgIgKAAgPIAAhtIgaAAIAAgXIAaAAIAAgqIAbAAIAAAqIAmAAIAAAXIgmAAIAABlQAAAMAEAGQADAFAFACIALACIAIgBIAEgBIAGAZIgIACIgMABQgMAAgLgFgAKcFDQgKgFgIgKQgHgKAAgPIAAhtIgaAAIAAgXIAaAAIAAgqIAbAAIAAAqIAlAAIAAAXIglAAIAABlQAAAMADAGQAEAFAFACIALACIAIgBIAEgBIAGAZIgIACIgMABQgMAAgLgFgADKFBQgMgHgIgPQgHgPAAgWIAAhvIAbAAIAABtQAAASALAMQAKAMARAAQALAAAKgFQAKgGAHgKQAHgLAAgQIAAhnIAbAAIAACuIgbAAIAAgdIgCAAQgFANgOAKQgMAJgUAAQgRAAgNgHgEAg4AFBQgGgGAAgIQAAgJAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAJQAAAEgDAGQgDAFgEADQgFACgGAAQgIAAgGgGgAQvFFIAAhtQAAgUgLgMQgLgLgTAAQgMAAgLAFQgLAHgGAKQgGAKAAAPIAABpIgaAAIAAjoIAaAAIAABVIADAAQAGgNAMgIQAMgIAVAAQARAAAOAHQAOAHAHAPQAIAOAAAXIAABugAKThhIAPhYIAdAAIgCAMQgCAMgEAQIgPAwgAd6ihQgSgMgKgTQgKgVAAgaQAAgbAKgVQAKgVASgLQARgLAYAAQAOAAANAEQAMAEAMALQALALAHAQQAGASAAAXIAAALIh/AAQABATAGALQAHAOAMAHQAMAHARAAQALAAAIgDQAJgDAGgGQAHgHACgIIAaAHQgDANgKAKQgKAKgOAGQgPAFgRAAQgZAAgTgLgAeHkqQgLAHgHANQgFALAAAMIBjAAQAAgPgGgLQgHgMgKgHQgLgGgOAAQgQAAgMAIgAbAihQgTgMgJgTQgKgUAAgbQAAgcAKgUQAKgUARgMQATgLAXAAQANAAAOAEQANAFALAKQAKAKAHARQAHAQAAAZIAAALIh/AAQAAASAHAMQAHAOAMAHQANAHAPAAQALAAAJgDQAJgDAFgGQAGgGAEgJIAaAHQgFAOgJAJQgJAKgPAGQgPAFgRAAQgYAAgTgLgAbNkqQgMAHgGANQgFAMgBALIBjAAQAAgQgFgKQgHgMgKgHQgMgGgNAAQgRAAgLAIgAH+ihQgSgNgEgVIAZgHQAEAPAKAGQAKAHARAAQATAAAKgHQAMgJAAgLQAAgIgHgHQgGgGgNgDIgdgHQgYgFgMgNQgLgLAAgTQAAgPAJgLQAIgMAOgGQAPgGASAAQAbAAAOALQAOALAHATIgYAHQgCgGgFgGQgEgGgHgDQgIgEgMAAQgQAAgKAHQgLAIAAALQAAAKAHAGQAJAGAOADIAaAHQAXAFAMAMQALAMAAASQAAAOgIANQgJAMgPAGQgQAHgUAAQgaAAgSgLgAFTihQgTgMgJgTQgKgUAAgbQAAgcAKgUQAKgUARgMQATgLAXAAQANAAAOAEQANAFALAKQAKAKAHARQAHAQAAAZIAAALIh/AAQAAASAHAMQAHAOAMAHQANAHAPAAQALAAAJgDQAJgDAFgGQAGgGAEgJIAaAHQgEAOgKAJQgJAKgPAGQgPAFgRAAQgYAAgTgLgAFgkqQgMAHgGANQgFALgBAMIBjAAQAAgOgFgMQgHgMgKgHQgMgGgNAAQgRAAgLAIgAwnihQgSgMgKgTQgJgUAAgbQAAgcAJgUQAKgUASgMQASgLAXAAQAOAAANAEQAOAFAKAKQALAKAHARQAGAQAAAZIAAALIh/AAQABASAGAMQAHAOAMAHQANAHAQAAQAKAAAJgDQAJgDAGgGQAGgGAEgJIAZAHQgEAOgJAJQgKAKgOAGQgPAFgRAAQgZAAgTgLgAwakqQgLAHgGANQgGALgBAMIBkAAQAAgOgGgMQgGgMgLgHQgLgGgOAAQgQAAgMAIgA5RihQgSgLgKgUQgKgUAAgbQAAgcAKgUQALgVAQgLQATgLAXAAQANAAAOAEQANAFALAKQALALAGAQQAHAQAAAZIAAALIh/AAQAAASAHAMQAHAOAMAHQAMAHARAAQAKAAAJgDQAIgDAHgGQAFgGAEgJIAaAHQgFAOgJAJQgJAKgPAGQgOAFgRAAQgZAAgTgLgA5EkqQgMAHgGANQgFAMgBALIBkAAQAAgPgGgLQgHgMgKgHQgMgGgNAAQgRAAgLAIgAsMieQgRgJgIgNQgKgNgBgTIAbAAQACAQANAKQANALARAAQAOAAAMgHQALgGAGgMQAHgMAAgPQAAgQgHgLQgHgNgLgGQgMgHgPAAQgKAAgLADQgLADgIAFIgagDIAOhyIB5AAIAAAZIhiAAIgIBEIACAAQAHgGAKgDQALgEAMAAQAVAAARAKQASALAIARQAKASAAAWQAAAXgKARQgKARgRALQgSAKgWAAQgUAAgQgIgEggzgClQgXgPgOgaQgNgcAAgkQAAgbAIgXQAHgVAOgQQANgQATgIQASgIAXAAQAUAAAOAFQARAGAMAKQAMAKAJAOQAIAMAEASIgdAAQgEgLgGgJQgGgIgJgIQgHgFgMgFQgMgDgLAAQgUAAgRALQgRAKgKAVQgKAUAAAfQAAAfAKAUQAJAVASALQASAKAVAAQAUAAAPgIQAPgIAJgRQAIgPABgUIg+AAIAAgZIBZAAIAAAZQAAAdgMAVQgMAVgWAMQgWAMgbAAQgfAAgXgPgEAg8gCcQgLgFgHgKQgHgJAAgQIAAhtIgbAAIAAgXIAbAAIAAgqIAaAAIAAAqIAmAAIAAAXIgmAAIAABlQAAALAEAHQAEAFAEACQAGACAGAAIAHgBIAEgBIAGAZIgIACIgMABQgMAAgKgFgADoicQgLgFgHgKQgHgKAAgPIAAhtIgbAAIAAgXIAbAAIAAgqIAaAAIAAAqIAmAAIAAAXIgmAAIAABlQAAALAEAHQAEAFAEACQAGACAGAAIAHgBIAEgBIAGAZIgIACIgMABQgMAAgKgFgAAkieQgMgHgIgPQgHgOAAgXIAAhvIAbAAIAABtQAAATAKALQALAMARAAQAKAAAKgFQALgGAHgKQAHgKAAgRIAAhnIAbAAIAACuIgbAAIAAgdIgCAAQgFANgOAKQgNAJgUAAQgQAAgNgHgAZWiaIAAh0QAAgTgKgJQgLgIgOAAQgSAAgLALQgKALAAARIAABxIgbAAIAAh3QAAgOgKgKQgJgJgPAAQgKAAgKAFQgJAHgGAJQgFAKAAAMIAABtIgbAAIAAiuIAaAAIAAAbIACAAQAFgNANgIQAMgIARAAQASAAALAIQAMAHAGAOIACAAQAGgNAOgIQANgIATAAQAXAAAPAOQAPAPAAAfIAAB0gATmiaIAAjoIAbAAIAADogASaiaIAAjoIAbAAIAADogAROiaIAAiuIAbAAIAACugAPbiaIgmiGIgDAAIgmCGIgaAAIg1iuIAcAAIAmCGIABAAIAmiGIAcAAIAlCFIACAAIAmiFIAcAAIg1CugAhCiaIAAhtQAAgUgLgMQgKgLgTAAQgNAAgKAFQgKAGgGALQgFAJAAAQIAABpIgbAAIAAiuIAaAAIAAAbIACAAQAHgNAMgIQALgIAVAAQARAAAOAHQAOAHAHAPQAHAPAAAWIAABugAj9iaIAAiuIAbAAIAACugAlJiaIAAh0QAAgTgLgJQgLgIgOAAQgSAAgKALQgKALAAARIAABxIgbAAIAAh3QAAgOgKgKQgKgJgPAAQgKAAgKAFQgJAHgFAJQgGAKAAAMIAABtIgaAAIAAiuIAaAAIAAAbIACAAQAFgNAMgIQANgIARAAQARAAALAIQAMAHAGAOIACAAQAHgNANgIQANgIAUAAQAXAAAPAOQAPAPAAAfIAAB0gAyQiaIAAh0QAAgTgLgJQgLgIgOAAQgSAAgKALQgKALAAARIAABxIgbAAIAAh3QAAgOgKgKQgKgJgPAAQgKAAgKAFQgIAGgGAKQgGAKAAAMIAABtIgaAAIAAiuIAaAAIAAAbIACAAQAFgNAMgIQANgIARAAQARAAALAIQAMAHAGAOIACAAQAHgNANgIQANgIAUAAQAXAAAPAOQAPAPAAAfIAAB0gA7oiaIhAiuIAdAAIAwCLIACAAIAwiLIAdAAIhACugA9miaIAAiuIAaAAIAACugAROlqQgFgHAAgGQAAgIAFgFQAHgGAHAAQAIAAAFAGQAGAFAAAIQAAAHgGAGQgFAFgIAAQgIAAgGgFgAj9lqQgGgHAAgGQAAgIAGgFQAGgGAHAAQAIAAAGAGQAGAFAAAIQAAAHgGAGQgFAFgJAAQgIAAgFgFgA9mlqQgGgGAAgHQAAgIAGgFQAFgGAIAAQAHAAAHAGQAFAFAAAIQAAAGgFAHQgGAFgIAAQgIAAgFgFg");
	this.shape.setTransform(-1.275,3.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#258BF5").s().p("EghgAJYQg+AAgsgsQgsgrAAg/IAAuDQAAg+AsgsQAsgsA+AAMBDBAAAQA+AAAsAsQAsAsAAA+IAAODQAAA+gsAsQgsAsg+AAg");
	this.shape_1.setTransform(-2.5,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#258BF5").s().p("AAoBGQg5AAgpgpQgpgoAAg6ICVAAQAAApACAMQAIAyAoAhIAAADg");
	this.shape_2.setTransform(222,53);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol51, new cjs.Rectangle(-232,-60,464,120), null);


(lib.Symbol49 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A2yGJIgHgCIAGgXQAKACAIAAQAIgBAFgGQAGgGAFgNIAFgOIhBivIAdAAIAwCLIACAAIAwiLIAeAAIhLDHQgEAOgIAJQgHAJgKAFQgIADgOAAIgMgBgA9rFHQgOgGgIgMQgIgLAAgSQAAgPAGgJQAGgKAKgGQAIgEAOgEIAygGQALgCADgDQAFgBAAgIIAAgBQAAgQgJgKQgJgJgTAAQgTAAgLAIQgLAJgEAJIgagJQAHgPALgKQAMgIANgEQANgDAOAAQAKAAAJACQAMACAKAGQAJAFAIANQAHANAAAUIAABzIgbAAIAAgXIgBAAQgDAGgHAGQgHAHgJAEQgLAFgPAAQgRAAgNgHgA8gD2IgmAGIgUAEQgJADgGAGQgFAHAAAJQAAAOAKAHQAKAHARAAQAQAAALgGQALgHAFgJQAGgJAAgMIAAgZQgBACgHADgAgwFBQgTgLgJgTQgKgWAAgZQAAgbAKgVQAKgVARgLQATgMAXABQAMgBAOAFQAMAEAMALQAKAJAHASQAHASAAAWIAAAMIh+AAQAAARAHANQAHAOAMAGQANAIAPAAQAKAAAIgDQAKgDAFgGQAHgHADgIIAaAHQgEANgKAKQgJAJgPAGQgPAGgQAAQgYAAgTgMgAgjC4QgMAIgGANQgFALgBAMIBiAAQAAgPgGgLQgFgMgLgHQgMgGgMgBQgRABgLAHgArPFBQgSgLgKgTQgKgWAAgZQAAgbAKgVQAKgVASgLQARgMAYABQAOgBANAFQAMAEAMALQALAKAHARQAGASAAAWIAAAMIh/AAQABATAGALQAHAOAMAGQAMAIARAAQALAAAIgDQAJgDAGgGQAHgHACgIIAaAHQgDAMgKALQgKAJgOAGQgPAGgRAAQgZAAgTgMgArCC4QgLAIgHANQgFALAAAMIBjAAQAAgPgGgLQgHgMgKgHQgLgGgOgBQgQABgMAHgAzuFBQgRgKgLgVQgJgTAAgcQAAgcAJgUQALgUARgLQASgLAYAAQAYAAARALQASAMAKATQAKAWAAAaQAAAagKAVQgKAUgSALQgSAMgXAAQgXAAgTgMgAziC6QgLAIgGARQgGAPAAARQAAARAGAPQAGAQALAJQAMAJASAAQARAAAMgJQAMgKAFgPQAGgNAAgTQAAgSgGgOQgFgQgMgJQgLgKgSAAQgTAAgLAKgEgg9AE+QgXgPgOgbQgNgbAAgkQAAgkANgcQAOgbAXgOQAWgPAfAAQASAAAPAGQAQAFAMAJQANALAIAOQAIAOADARIgcAAQgCgMgGgJQgHgJgIgHQgJgGgLgDQgNgDgJAAQgVgBgRALQgRALgLAVQgKAVAAAeQAAAeAKAVQALAVARAKQAQALAWAAQALAAALgDQAJgCALgIQAJgGAGgJQAGgLACgLIAcAAQgDARgIAQQgIAOgNAJQgMAKgQAFQgRAFgQABQgeAAgXgPgAoNFHQgLgFgHgLQgHgIAAgRIAAhtIgbAAIAAgWIAbAAIAAgqIAaAAIAAAqIAmAAIAAAWIgmAAIAABmQAAAKAEAIQAEAFAEACQAGACAGAAIAHgBIAEgBIAGAYIgIACIgMABQgMAAgKgEgAwxFFQgMgIgIgPQgHgOAAgXIAAhuIAaAAIAABtQAAASALAMQAKAMASAAQAKgBAKgEQALgGAHgKQAHgLAAgQIAAhnIAaAAIAACuIgaAAIAAgdIgCAAQgGANgNAJQgNAJgUAAQgQAAgNgGgAHwFFQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAIQAAAGgDAFQgDAEgFADQgFADgFAAQgIAAgGgGgAGBFJIAAhtQAAgUgLgMQgLgMgSAAQgMABgLAFQgLAHgFAKQgGAKAAAPIAABpIgbAAIAAiuIAaAAIAAAbIADAAQAGgOAMgIQANgHATAAQASAAANAGQAOAIAHAPQAIAOAAAXIAABugADFFJIAAiuIAbAAIAACugAiaFJIAAh1QAAgTgKgIQgLgJgOAAQgSABgLAKQgKAMAAARIAABxIgbAAIAAh3QAAgPgKgKQgJgIgQgBQgKABgJAFQgJAGgGAKQgFAJAAANIAABtIgbAAIAAiuIAaAAIAAAbIACAAQAFgOANgIQALgHASAAQASAAALAHQAMAIAGAOIACAAQAGgOAOgIQANgHATAAQAXAAAPAOQAPAPAAAeIAAB1gAs4FJIAAjpIAaAAIAADpgA5dFJIAAhtQAAgUgLgMQgKgMgTAAQgNABgKAFQgKAGgGALQgGAKAAAPIAABpIgaAAIAAiuIAaAAIAAAbIACAAQAFgNANgJQANgHAUAAQARAAAOAGQAOAJAGAOQAIAOAAAXIAABugAHwEIIAAgBQAAgWAEgNQAEgLAIgKQAJgIAKgHIANgJQAFgFADgJQADgGAAgJQAAgLgFgJQgFgIgJgFQgIgEgMAAQgIAAgJAEQgKAEgFAIQgGAJgBANIgcAAQAAgTAKgPQAJgNAPgHQAQgIARAAQAVAAAOAJQAOAGAJAPQAIAOAAASQAAANgDAJQgEAJgHAJQgJAKgIAFQgJAFgHAHQgGAIgDAJQgDAJAAAPIAAABgADGB5QgGgGAAgHQAAgIAGgGQAFgFAIAAQAIAAAFAFQAGAGAAAIQAAAHgGAGQgFAEgIABQgIgBgFgEgAXJhVQgPgGgIgHQgKgKgFgHIAVgPIAKAKQAFAHAKAEQAKAEAPABQAWAAANgKQAOgLAAgWIAAgjIgCAAIgJAMQgFAHgKAFQgKAGgRAAQgVAAgRgLQgRgJgKgUQgJgUAAgaQAAgcAJgSQAKgWAQgKQARgKAWgBQARABAKAFQALAGAFAHIAIAMIADAAIAAgdIAaAAIAAC0QAAAXgKAOQgKANgSAIQgRAGgVABQgSgBgPgEgAXNkmQgMAKgFANQgFAOAAASQAAASAFAPQAHAOAKAHQALAJASAAQAQgBALgHQALgHAGgOQAGgOAAgUQAAgSgGgPQgFgOgMgIQgLgJgQABQgRAAgMAIgAwXhdIAEgTIAFgbIAFgrIAdAAIgCANQgBAKgEASIgPAwgAZ8iYQgMgFgJgNQgIgLAAgTQAAgPAGgIQAGgLAKgFQAJgEAMgEIAygHQALgBAEgCQAFgDAAgGIAAgBQAAgRgKgJQgJgKgSAAQgTAAgLAJQgLAHgFALIgZgJQAGgQAMgJQAMgKANgDQANgDAOgBQAJAAAKACQANADAIAFQAKAGAIANQAGAMAAAVIAABzIgaAAIAAgYIgCAAQgCAGgHAHQgIAHgJAEQgKAFgQgBQgRABgNgHgAbIjpIgnAFQgKACgJADQgKADgFAGQgFAGAAAKQAAAOAKAHQAKAHAQAAQAQAAALgGQALgGAGgKQAGgKAAgLIAAgZIgIAFgAk/iYQgNgFgJgNQgIgNAAgRQAAgPAGgIQAGgKAKgGQAJgEANgEIAygHQALgBAEgCQAEgDAAgGIAAgBQAAgRgJgJQgJgKgTAAQgSAAgMAJQgLAIgEAKIgagJQAIgQALgJQAKgJAPgEQAMgDAOgBQAKAAAKACQALADAKAFQAKAHAHAMQAHANAAAUIAABzIgbAAIAAgYIgBAAQgCAGgHAHQgHAHgKAEQgLAFgPgBQgRABgNgHgAjzjpIgnAFQgLACgJADQgJADgFAGQgGAHAAAJQAAAPALAGQAKAHAQAAQAQAAALgGQAKgGAHgKQAFgKAAgLIAAgZQgBACgGADgA4UiYQgMgFgJgNQgIgNAAgRQAAgPAGgIQAGgKAKgGQAJgEAMgEIAygHQALgBAEgCQAFgDAAgGIAAgBQAAgRgKgJQgJgKgSAAQgTAAgLAJQgLAHgFALIgZgJQAGgPAMgKQALgJAOgEQANgDAOgBQAJAAAKACQAMADAJAFQALAHAHAMQAGAMAAAVIAABzIgaAAIAAgYIgCAAQgCAGgHAHQgIAHgJAEQgKAFgQgBQgRABgNgHgA3IjpIgnAFQgKACgJADQgKADgFAGQgFAHAAAJQAAAPAKAGQAKAHARAAQAQAAAKgGQALgGAGgKQAGgKAAgLIAAgZQgBACgHADgAeridQgSgMgKgTQgKgWAAgaQAAgaAKgVQAKgVASgLQASgMAXAAQAOABANAEQANAFALAJQALALAHAQQAGATAAAXIAAALIh/AAQABARAGANQAHANAMAIQANAHAQAAQALAAAIgDQAJgDAGgHQAHgGACgIIAaAHQgEAOgJAJQgKAJgOAHQgPAFgRAAQgZAAgTgLgAe4kmQgLAHgGANQgGALAAAMIBjAAQAAgPgGgLQgGgMgLgHQgLgGgOAAQgQgBgMAJgAN5idQgSgMgKgUQgKgVAAgaQAAgaAKgWQAKgUASgMQARgKAZgBQAYABARAKQASAMAKAUQAKAWAAAaQAAAagKAVQgKAUgSAMQgSALgXAAQgYAAgSgLgAOFklQgLAJgGAQQgGAPAAARQAAARAGAQQAGAPALAJQAMAJASAAQARAAAMgJQAMgKAFgOQAGgQAAgRQAAgRgGgPQgFgPgMgKQgLgJgSAAQgTAAgLAJgAGAidQgTgMgJgTQgKgUAAgcQAAgcAKgTQAKgVARgLQATgMAXAAQANABAOAEQANAFALAJQAKALAHAQQAHARAAAZIAAALIh/AAQAAARAHANQAHANAMAIQANAHAPAAQALAAAJgDQAJgDAFgHQAGgFAEgJIAaAHQgFAOgJAJQgJAJgPAHQgPAFgRAAQgYAAgTgLgAGNkmQgMAHgGANQgFAMgBALIBjAAQAAgQgFgKQgHgMgKgHQgMgGgNAAQgRgBgLAJgA1YidQgSgMgJgVQgKgTAAgbQAAgbAKgUQAKgVASgLQARgMAYAAQATABAOAGQAPAIAJALQAJAMADARIgbAAQgDgMgKgJQgKgJgTAAQgQgBgLAJQgNAIgFAOQgHAPAAAUQAAAUAGAPQAHAPAMAJQALAIAQAAQAKAAAJgEQAJgEAGgHQAFgFADgLIAbAAQgDAQgIAMQgJANgPAGQgPAIgTAAQgYAAgSgLgA7CiaQgPgGgIgOQgJgMAAgSIAcAAQAAAKAFAHQAEAHAJAFQAKADAKAAQALAAAKgEQAIgGAFgKQAEgKAAgOIAAimIAcAAIAACmQAAAXgIAPQgIAPgPAIQgQAJgTgBQgTABgPgIgAdAiYQgLgFgHgKQgHgKAAgQIAAhtIgaAAIAAgXIAaAAIAAgpIAbAAIAAApIAlAAIAAAXIglAAIAABmQAAALADAGQAEAGAFACQAFACAGgBIAHAAIAFgBIAFAZIgHABIgNABQgMAAgKgEgAT7iYQgLgFgHgKQgHgKAAgQIAAhtIgbAAIAAgXIAbAAIAAgpIAaAAIAAApIAmAAIAAAXIgmAAIAABmQAAAMAEAFQADAFAFADIAMABIAHAAIAEgBIAGAZIgIABIgMABQgMAAgKgEgABSiYQgLgFgHgKQgHgKAAgQIAAhtIgaAAIAAgXIAaAAIAAgpIAbAAIAAApIAlAAIAAAXIglAAIAABmQAAAMADAFQADAFAGADQAFACAGgBIAHAAIAFgBIAFAZIgHABIgNABQgMAAgKgEgAh7iYQgLgFgHgKQgHgLAAgPIAAhtIgbAAIAAgXIAbAAIAAgpIAbAAIAAApIAlAAIAAAXIglAAIAABmQAAAMADAFQAEAGAFACIALABIAHAAIAFgBIAFAZIgIABIgMABQgMAAgKgEgEAhNgCaQgGgGAAgIQAAgJAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAJQAAAEgDAGQgDAFgEADQgFACgGAAQgIAAgGgGgASKiWIAAhtQAAgUgLgMQgKgLgTAAQgMAAgLAFQgKAGgGAKQgGALAAAPIAABpIgaAAIAAivIAZAAIAAAcIADAAQAFgMANgKQANgHAUgBQARAAAOAHQANAIAHAOQAIAPAAAXIAABugALqiWIAAivIAaAAIAAAbIACAAQAEgNANgIQAMgIAQAAIAOAAIAAAbIgGgBIgKAAQgNAAgKAFQgKAFgGAKQgFAJAAAMIAABugAKCiWIAAiYIgcAAIAAgXIAcAAIAAgXQAAgOAHgMQAIgJALgGQAMgEALAAQAKgBAHACIAJADIgIAYIgFgCIgKgBQgNAAgGAGQgGAIAAAMIAAARIAnAAIAAAXIgnAAIAACYgAEWiWIAAhtQAAgUgKgMQgLgLgTAAQgNAAgLAFQgLAHgFAJQgGAMAAAOIAABpIgbAAIAAjoIAbAAIAABVIACAAQAGgMANgKQALgHAWgBQASAAANAHQAOAIAHAOQAHAPAAAXIAABugAn6iWIAAh0QAAgUgLgIQgLgIgOAAQgSgBgKALQgKAMAAAQIAAByIgcAAIAAh3QAAgPgJgJQgKgKgPABQgKAAgKAFQgIAFgGAKQgGAKAAANIAABtIgaAAIAAivIAZAAIAAAcIADAAQAFgNAMgJQAMgHASgBQARABALAHQAMAIAGAOIACAAQAHgNANgJQANgHATgBQAYAAAPAPQAPAPAAAfIAAB0gAtciWIAAjoIAcAAIAADogAxTiWIhBhSIgTARIAABBIgbAAIAAjoIAbAAIAACHIADAAIBNhOIAhAAIhKBLIBPBkgA99iWIAAivIAbAAIAACvgA/OiWIAAhoIh8AAIAABoIgcAAIAAjoIAcAAIAABnIB8AAIAAhnIAdAAIAADogAsNkuIAAhQIAZAAIAABQgA98lmQgGgGAAgIQAAgHAGgFQAFgGAIAAQAIAAAFAGQAGAFAAAHQAAAIgGAGQgFAEgIAAQgIAAgFgEg");
	this.shape.setTransform(1.875,3.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E5E5EA").s().p("EghqAJYQg+AAgsgsQgsgsAAg+IAAuDQAAg+AsgsQAsgsA+AAMBDVAAAQA+AAAsAsQAsAsAAA+IAAODQAAA+gsAsQgsAsg+AAg");
	this.shape_1.setTransform(2.5,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E5E5EA").s().p("AhjBGIAAgDQAngiAJgxQACgLAAgqICVAAQAAA6gpAoQgpApg5AAg");
	this.shape_2.setTransform(-223,53);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol49, new cjs.Rectangle(-233,-60,466,120), null);


(lib.Symbol48 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EAuKACZIgHgCIAGgXQAKACAIAAQAIgBAFgGQAHgIAEgLIAFgOIhBiuIAdAAIAxCKIABAAIAxiKIAdAAIhKDGQgGAOgHAJQgHAJgKAEQgIAEgOABIgMgCgATDCZIgIgCIAHgXQAKACAHAAQAIgBAGgGQAFgGAGgNIAFgOIhBiuIAdAAIAwCKIACAAIAwiKIAdAAIhKDGQgFAOgHAJQgIAJgJAEQgJAEgNABIgMgCgEAo/ABXQgOgGgIgMQgIgMAAgRQAAgPAGgKQAGgKAKgFQAKgDAMgDIAygHQALgCADgDQAFgBAAgIIAAgBQAAgQgJgKQgJgJgTAAQgTAAgLAIQgLAIgEAKIgagJQAHgPALgKQAMgIANgEQAOgEANABQAKAAAKACQALACAKAGQAJAFAIANQAHAMAAAVIAAByIgbAAIAAgXIgBAAQgDAFgGAHQgIAHgJAEQgLAEgPABQgRgBgNgGgEAqKAAFIgmAHQgLABgJADQgJADgFAGQgGAGAAAKQAAAOAKAHQAKAHARAAQAQAAALgGQALgGAFgKQAGgJAAgMIAAgYQgBABgHACgAb1BXQgNgGgIgMQgIgMAAgRQAAgPAGgKQAGgKAJgFQAJgDANgDIAygHQALgCAEgDQAEgBAAgIIAAgBQAAgQgJgKQgJgJgSAAQgTAAgMAIQgKAJgFAJIgZgJQAGgPAMgKQAMgIANgEQAMgEAPABQAJAAAKACQALACAKAGQAKAFAHANQAHANAAAUIAAByIgbAAIAAgXIgBAAQgDAFgGAHQgHAHgKAEQgLAEgPABQgRgBgNgGgAdBAFIgNADIgaAEIgUAEQgIADgGAGQgGAHAAAJQAAAPALAGQAKAHAQAAQAQAAALgGQAMgHAFgJQAFgJAAgMIAAgYQgBABgGACgAJxBXQgOgGgIgMQgIgMAAgRQAAgPAGgKQAFgJALgGQAIgDAOgDIAygHQALgCADgDQAFgBAAgIIAAgBQAAgQgJgKQgJgJgTAAQgTAAgLAIQgLAJgEAJIgagJQAHgPALgKQALgIAOgEQANgEAOABQAKAAAJACQAMACAKAGQAJAFAIANQAHANAAAUIAAByIgbAAIAAgXIgCAAQgCAFgHAHQgGAGgLAFQgKAEgPABQgRgBgNgGgAK8AFIgnAHQgLABgIADQgIADgHAGQgFAHAAAJQAAAPAKAGQAKAHARAAQAQAAALgGQAKgGAGgKQAGgKAAgLIAAgYQgBABgHACgEArsABRQgRgLgFgWIAZgHQAEAPAKAGQAKAHARAAQATAAALgIQALgIAAgLQAAgJgHgHQgGgFgNgEIgdgGQgYgGgLgLQgMgNAAgRQAAgOAJgNQAIgLAPgGQANgHAUABQAaAAAOALQAPALAGATIgYAGQgCgGgEgFQgEgFgIgEQgIgFgLAAQgRAAgKAIQgLAHAAALQAAAKAIAHQAHAFAPAEIAaAHQAWAFANALQAMAMAAASQAAAOgJANQgIALgQAHQgQAHgUAAQgaAAgSgMgEAmNABRQgTgLgJgUQgKgVAAgZQAAgaAKgVQAKgVARgLQATgLAXAAQANgBAOAFQAMAEAMALQAKAKAHARQAHASAAAWIAAALIh/AAQAAARAHANQAHAOAMAGQANAIAPAAQALAAAIgDQAKgDAFgGQAHgHADgJIAaAIQgEANgKAKQgJAKgPAFQgPAGgRAAQgYAAgTgMgEAmagA3QgMAIgGANQgFALgBAMIBjAAQAAgPgGgMQgFgMgLgGQgMgHgNAAQgRABgLAHgEAh5ABRQgTgKgJgVQgKgTAAgbQAAgcAKgTQAKgVARgLQASgLAXAAQAOgBANAFQANAEAMALQALALAGAQQAGAPAAAZIAAALIh+AAQAAASAGAMQAHAOANAGQAMAIAQAAQALAAAIgDQAJgDAGgGQAGgGAEgKIAaAIQgFAOgJAJQgKAKgOAFQgPAGgRAAQgZAAgSgMgEAiGgA3QgMAIgGANQgFALgBAMIBjAAQAAgPgGgMQgGgMgKgGQgMgHgOAAQgQABgLAHgAewBSQgRgLgKgVQgJgVAAgaQAAgaAJgWQAKgTARgLQAQgLAXAAQAQgBAKAGQALAGAFAHQAGAIACADIACAAIAAhWIAbAAIAADoIgaAAIAAgbIgDAAIgIANQgHAHgJAFQgLAGgQAAQgVAAgRgLgAe9g2QgKAJgHAPQgFAPAAARQAAARAFARQAGAOAMAKQALAJARAAQAQAAALgJQAMgJAFgOQAGgPAAgUQAAgSgGgPQgGgPgLgIQgLgJgQAAQgRABgMAIgAphBRQgRgKgLgVQgJgUAAgbQAAgbAJgUQALgUARgLQASgLAYAAQAYAAARALQASAMAKATQAKAVAAAaQAAAagKAVQgKAUgSALQgSAMgXAAQgXAAgTgMgApVg1QgLAJgGAPQgGAQAAAQQAAARAGAPQAGAQALAJQAMAJASAAQARAAAMgJQAMgKAFgPQAGgNAAgTQAAgRgGgPQgFgOgMgKQgLgKgSAAQgTAAgLAKgAwyBRQgRgKgLgVQgJgUAAgbQAAgbAJgUQALgUARgLQASgLAYAAQAYAAARALQASAMAKATQAKAVAAAaQAAAagKAVQgKAUgSALQgSAMgXAAQgXAAgTgMgAwmg1QgLAJgGAPQgGAQAAAQQAAARAGAPQAGAQALAJQAMAJASAAQARAAAMgJQAMgKAFgPQAGgNAAgTQAAgRgGgPQgFgOgMgKQgLgKgSAAQgTAAgLAKgA6SBRQgRgKgLgVQgKgVAAgaQAAgaAKgVQALgUARgLQARgLAZAAQAYAAARALQASALAKAUQAKAVAAAaQAAAagKAVQgKAUgSALQgSAMgXAAQgYAAgSgMgA6Gg1QgLAJgGAPQgGAQAAAQQAAARAGAPQAGAQALAJQAMAJASAAQARAAAMgJQAMgKAFgPQAGgPAAgRQAAgQgGgQQgFgOgMgKQgLgKgSAAQgTAAgLAKgA9FBRQgSgLgKgUQgJgUAAgbQAAgbAKgTQAKgVARgLQASgLAXAAQATgBAPAHQAPAIAJAMQAJALACARIgaAAQgDgMgLgJQgKgKgSAAQgQABgMAHQgMAKgGAOQgGAOAAATQAAAUAGAPQAHAQALAHQAMAJAQAAQAKAAAJgEQAIgEAGgHQAFgFAEgKIAaAAQgCAPgJAMQgJAMgOAIQgPAHgTAAQgZAAgRgMgEghVABRQgRgLgFgWIAZgHQAEAPAKAGQAKAHARAAQATAAALgIQALgIAAgLQAAgJgHgHQgGgFgNgEIgdgGQgYgGgLgLQgMgNAAgRQAAgOAJgNQAIgLAPgGQANgHAUABQAaAAAOALQAPALAGATIgYAGQgCgGgEgFQgEgFgIgEQgIgFgLAAQgRAAgKAIQgLAHAAALQAAAKAIAHQAHAFAPAEIAaAHQAWAFANALQAMAMAAASQAAAOgJANQgIALgQAHQgQAHgUAAQgaAAgSgMgEgj8ABRQgSgMgEgVIAZgHQAEAPAKAGQAJAHASAAQATAAAKgIQAMgIAAgLQAAgJgHgHQgGgFgNgEIgdgGQgYgGgMgLQgLgMAAgSQAAgOAJgNQAIgLAOgGQAPgHASABQAbAAAOALQAQAMAFASIgYAGQgCgFgFgGQgDgFgIgEQgIgFgMAAQgQAAgKAIQgLAHAAALQAAAKAHAHQAJAFAOAEIAaAHQAXAFAMALQALALAAATQAAAOgIANQgIALgQAHQgQAHgUAAQgaAAgSgMgEgmnABRQgTgLgJgUQgKgTAAgbQAAgcAKgTQAKgVARgLQATgLAXAAQANgBAOAFQANAEALALQAKAKAHARQAHAPAAAZIAAALIh/AAQAAARAHANQAHAOAMAGQANAIAPAAQALAAAJgDQAJgDAFgGQAGgGAEgKIAaAIQgFAOgJAJQgJAKgPAFQgPAGgRAAQgYAAgTgMgEgmagA3QgMAIgGANQgFAMgBALIBjAAQAAgQgFgLQgHgMgKgGQgMgHgNAAQgRABgLAHgEgpbABRQgSgLgJgUQgKgWAAgZQAAgZAKgVQAKgVASgLQARgLAYAAQATgBAOAHQAQAIAIAMQAKALACARIgbAAQgDgMgKgJQgKgKgTAAQgQABgLAHQgMAJgGAPQgHAOAAATQAAAVAHAOQAGAQAMAHQAMAJAPAAQAKAAAJgEQAIgDAHgIQAGgHACgIIAbAAQgCAOgJANQgJANgPAHQgOAHgUAAQgYAAgSgMgEgsOABRQgRgLgKgUQgJgUAAgbQAAgbAJgTQAKgVASgLQASgLAXAAQAUgBANAHQAQAIAJAMQAJAMACAQIgaAAQgEgMgKgJQgKgKgSAAQgQABgMAHQgMAJgGAPQgHAQAAARQAAATAHAQQAHAQALAHQAMAJAQAAQAJAAAKgEQAIgEAGgHQAFgFAEgKIAaAAQgCAPgJAMQgJAMgOAIQgPAHgTAAQgYAAgTgMgAFSBWQgLgEgHgLQgHgIAAgQIAAhtIgbAAIAAgWIAbAAIAAgqIAaAAIAAAqIAmAAIAAAWIgmAAIAABlQAAAKAEAIQADAFAFACIAMACIAHgBIAEgBIAGAYIgIACIgMACQgMgBgKgFgABCBVQgMgIgIgPQgHgOAAgXIAAhtIAbAAIAABsQAAATAKALQALAMARAAQAKgBAKgFQALgFAHgKQAHgKAAgRIAAhmIAbAAIAACtIgbAAIAAgdIgCAAQgFANgOAKQgNAIgUABQgQgBgNgGgA0QBWQgLgEgHgLQgHgIAAgQIAAhtIgbAAIAAgWIAbAAIAAgqIAaAAIAAAqIAmAAIAAAWIgmAAIAABlQAAAKAEAIQADAFAFACQAGACAGAAIAHgBIAEgBIAGAYIgIACIgMACQgMgBgKgFgAaUBZIAAh0QAAgTgLgIQgLgJgNAAQgTAAgKAMQgKALAAARIAABwIgbAAIAAh2QAAgOgKgLQgJgIgQgBQgKAAgJAGQgKAHgFAJQgFAIAAAOIAABsIgbAAIAAitIAaAAIAAAbIACAAQAGgPAMgGQALgIASAAQARAAALAIQAMAHAHAOIABAAQAHgMANgJQANgIAUAAQAXAAAPAOQAPAPAAAeIAAB0gARyBZIAAjoIAaAAIAADogAQmBZIAAitIAbAAIAACtgAPaBZIAAh0QAAgTgLgIQgLgJgOAAQgSAAgKAMQgKALAAARIAABwIgbAAIAAh2QAAgOgKgLQgKgIgPgBQgKAAgKAGQgIAGgGAKQgGAJAAANIAABsIgaAAIAAitIAaAAIAAAbIACAAQAFgOAMgHQANgIARAAQARAAALAIQAMAHAGAOIACAAQAHgOANgHQANgIAUAAQAXAAAPAOQAPAPAAAeIAAB0gAH5BZIAAiXIgcAAIAAgWIAcAAIAAgZQAAgOAHgLQAHgJALgFQANgGALAAQAKABAGABIAJADIgHAXIgGgCIgJgBQgOAAgGAIQgFAHAAAMIAAASIAnAAIAAAWIgnAAIAACXgAGhBZIAAitIAbAAIAACtgADhBZIAAjoIAbAAIAADogAgkBZIAAh0QAAgTgLgIQgLgJgNAAQgTAAgKAMQgKALAAARIAABwIgbAAIAAh2QAAgOgKgLQgJgIgQgBQgKAAgJAGQgKAHgFAJQgFAIAAAOIAABsIgbAAIAAitIAaAAIAAAbIACAAQAGgPAMgGQALgIASAAQARAAAMAIQALAHAHAOIABAAQAHgNAOgIQAMgIAUAAQAXAAAPAOQAPAPAAAeIAAB0gAm/BZIAAitIAaAAIAAAaIABAAQAGgNAMgIQAMgIAQAAIAOABIAAAbIgGgBIgKgBQgNAAgKAFQgKAFgGAKQgFAJAAAMIAABtgArfBZIAAiXIgcAAIAAgWIAcAAIAAgZQAAgOAIgLQAHgJALgFQAMgGAMAAQAKABAGABIAJADIgIAXIgFgCIgKgBQgNAAgGAIQgGAHAAAMIAAASIAnAAIAAAWIgnAAIAACXgAuQBZIAAjoIAbAAIAADogAzBBZIAAitIAaAAIAAAaIACAAQAEgMANgJQAMgIAQAAIAOABIAAAbIgGgBIgKgBQgNAAgKAFQgKAGgFAJQgGAJAAAMIAABtgA2BBZIAAhsQAAgUgLgMQgKgMgTAAQgNAAgKAGQgKAGgGALQgGAKAAAPIAABoIgaAAIAAitIAaAAIAAAbIACAAQAFgMANgJQANgIAUAAQARAAAOAGQANAIAHAPQAIAOAAAWIAABugEgtoABZIgXhCIhfAAIgXBCIgeAAIBWjoIAdAAIBVDogEgvVgABIBNAAIgmhoIgCAAgAQmh3QgGgGAAgGQAAgIAGgGQAGgFAHAAQAIAAAGAFQAFAGAAAIQAAAHgFAFQgFAFgJABQgIgBgFgFgAGhh3QgFgFAAgHQAAgIAFgGQAGgFAIAAQAHAAAGAFQAGAGAAAIQAAAGgGAGQgFAFgIABQgJgBgFgFg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol48, new cjs.Rectangle(-309.1,-15.4,618.3,30.9), null);


(lib.Symbol35 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0071").s().p("EgEjAmJQiHg5hnhnQhohog5iHQg7iMAAiYMAAAg2rQAAiZA7iLQA5iGBohoQBnhoCHg5QCMg7CXAAQCYAACMA7QCHA5BnBoQBoBoA5CGQA7CLAACZMAAAA2rQAACYg7CMQg5CHhoBoQhnBniHA5QiMA7iYAAQiXAAiMg7g");
	this.shape.setTransform(37.5006,125,0.5047,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol35, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol33 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#436AE6").s().p("AjJFrQgggVgQgkQgJgWgBgYIAAoIQAAgiARgcQAQgdAcgQQAdgRAhAAIEjAAQAcAAAWAOQAYAOAOAYQAPAagBAdQAAAcgOAZQgOAZgYAOQgXAPgdAAIinAAIgBBBICKABQAXABAVAIQAVAIAQARQAPAOAIASQAIASAAAUQABArghAeQgiAegsABIiLAAIgBBEICgAAQAwAAAhAhQASAOAHATQAIAUABAVQAAAsghAeQghAfguAAIkcAAIAAABQgkAAgdgWg");
	this.shape.setTransform(520.75,39.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#436AE6").s().p("Ag6GHQhiAAhYgsQgigTgVgdQgQgeABggQAAggASgaQALgUAUgMQAUgMAYAAQAVAAAQAEICDAhIASADQAQADAVABQAPAAAOgFQAPgDALgJQAKgHAAgLQAAgOgMgFIgdgLIiWgoQg0gNgtgbQgrgbgYgrQgWgvAAgxQAAgtAQgoQAQgpAeggQAlgoAzgYQA7gbBAgIQAcgDAaAAQA5AAA4AQQAwAMApAcQAcAWALAiQAEARABAUQABAfgSAZQgPAWgVAMQgWALgZgBQgjgBgfgJIgIgDIhhgZIgFgBQgEgCgEABQgWgDgTAMQgJAHAAALQAAAJAGADQAIAGAJABICZAqQAwANAtAWQAaAOAYAVQAWATAPAZQAPAZAIAcQAHAcAAAcQgBBZg6BBQhbBviyAAIgtgCg");
	this.shape_1.setTransform(455.6938,39.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#436AE6").s().p("AhUFlQglglABgzIAAobQAAgYAJgXQAJgWASgRQAdgdApgGQAogFAjAUQAdARAPAcQAQAdAAAhIAAIdQAAAZgJAWQgJAYgRAQQgkAjgxgBIgDAAQgwAAgigkg");
	this.shape_2.setTransform(403.9471,39.6279);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#436AE6").s().p("AksF8QghgRgWgdQgXgjgMgpIiKn5QgDgLgBgMQACgdANgZQANgaAbgSQAXgRAggFQAwgDAmAdQAmAeAKAvIBaE3IBclBQAUhHAwgSQAUgIAUABQAlAAAcAZQAeAdALAqIBaFAIBbk3QAKgvAmgdQAmgdAxADQAeAEAZASQAZARAOAcQAOAZABAdQAAAMgEAJIiKH5QgOA9gtApQgtAkg4gCQg0AAgqgfQgrgigQg0IhNj0IhOD1QgLAjgWAbQgWAaggAPQghAPghgBQglABghgPg");
	this.shape_3.setTransform(331.7,39.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0071").s().p("AiJGBQgjAAgdgWQgggVgQgkQgKgWAAgYIAAoIQAAghARgdQARgdAbgQQAcgRAiAAIEjAAQAbAAAXAOQAYAOAOAYQAOAZAAAdQAAAdgOAZQgOAZgYAOQgYAPgcAAIinAAIgBBBICKABQAXAAAVAJQAUAIARAQQAhAegBApQAAArghAeQghAegtABIiKAAIgBBEICfAAQAwAAAiAhQAQAOAJATQAIAWAAATQABAsghAeQgiAgguAAg");
	this.shape_4.setTransform(247.5265,39.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0071").s().p("Ag/F0QgcgRgQgcQgQgcAAghIAAm7IhUgBQgrACgeghQgfgfABgsQAAgbAOgaQAOgYAYgOQAXgOAcABIGfAAQAbAAAaAPQAYAPANAYQAOAZgBAdQgBAtgfAeQgdAegqAAIhZAAIgBG8QAAAggQAcQgRAcgbAPQgbARggAAQggAAgegRg");
	this.shape_5.setTransform(184.6767,39.9717);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0071").s().p("AC8FyQghgZgNgnIgMgkIkBAAIgOAkQgNAnggAYQgeAYgnAAQgbgBgXgKQghgNgWgdQgUgdABgjQACgiAMgfIC3nWQAWg9AzgmQAygjA7AAQA9AAAyAjQAzAmAWA9IC2HWQAMAfACAjQAAAjgTAcQgVAegiANQgXALgcAAQgmAAgdgYgAg5A6IByABIg5jNIAAgBIgBAAg");
	this.shape_6.setTransform(121.3476,39.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0071").s().p("AAcGJQgxgBgugHQhGgLg9ggQg7gfgrgwQgugzgZg8QgehIAAhNQgBhjAyhYQA2hbBZg3QBqhBB5ADQAUAAAcACQA3AEA1ARQAxAQAuAbQBaA8AABDQgBAtgkAcQgbAYgkgBQgegBgcgMIhEgkQg3gbhBgDQgpAAgnASQgkASgYAjQgYAlgHAsQgDAQgBANQAAARAEARQAHAqAZAmQAZAhAkASQAoASAqgBQAbAAAbgHQAxgFAeglIhBgBQgtABggghQgeggABgtQAAgcAOgZQANgYAZgOQAZgOAdAAIDNAAQBwAAABB7QgCApgGAhQgJA0gbAvQgeA4gyApQgyApg9AVQhBAVhFAAIgGAAg");
	this.shape_7.setTransform(40.25,39.5725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol33, new cjs.Rectangle(0,0,546.7,79.2), null);


(lib.Symbol20 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0071").s().p("Eg6lATiMAAAgnDMB1LAAAMAAAAnDg");
	this.shape.setTransform(375,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol20, new cjs.Rectangle(0,0,750,250), null);


(lib.Symbol9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image25();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol9, new cjs.Rectangle(0,0,160,160), null);


(lib.Symbol4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Eg6lATiMAAAgnDMB1LAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(-375,-125,750,250), null);


(lib.shape17Hit = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006666").s().p("EiM3APDIAA+FMEZvAAAIAAeFg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-901.6,-96.3,1803.3000000000002,192.6);


(lib.ClipGroup_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AifCgIAAk/IE/AAIAAE/g");
	mask.setTransform(16,16);

	// Layer_3
	this.instance = new lib.Image();
	this.instance.setTransform(0,0,0.5,0.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ClipGroup_1, new cjs.Rectangle(0,0,32,32), null);


(lib.Symbol50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EAhdACXQgPgFgIgHQgKgKgFgHIAVgQIAJALQAGAHAJAEQALAEAQABQAVAAANgKQAOgLAAgWIAAgjIgDAAIgIAMQgFAHgKAFQgLAGgRAAQgUAAgRgLQgQgIgLgVQgKgTAAgaQAAgaAKgUQAKgWAQgKQAQgKAXgBQARABAKAFQALAGAEAHIAJAMIADAAIAAgdIAZAAIAACzQABAYgLANQgKANgRAIQgRAGgUABQgTgBgPgFgEAhhgA4QgLAJgGAOQgFAQgBAQQABARAFAPQAHAOAKAIQALAIASAAQAPgBAMgHQAKgHAHgOQAFgOAAgTQAAgSgFgPQgGgOgLgIQgLgJgQABQgSAAgLAIgAVfBPQgTgLgJgTQgKgWAAgaQAAgZAKgVQAKgVASgLQASgMAXAAQAOABANAEQAMAEAMAKQALALAGAQQAHATAAAXIAAAKIh/AAQABARAGANQAHANAMAIQAMAHARAAQAKAAAIgDQAKgDAGgHQAGgGADgIIAaAHQgEAOgKAJQgJAJgPAHQgPAFgQAAQgaAAgSgMgAVsg4QgLAHgHANQgFALgBAMIBkAAQAAgPgHgLQgEgMgMgHQgMgGgNAAQgQgBgMAJgAOKBPQgSgLgKgUQgKgVAAgaQAAgZAKgWQAKgTASgNQARgKAYgBQAZABAQAKQASALAKAVQAKAWAAAZQAAAagKAVQgKAVgSAKQgRAMgYAAQgXAAgSgMgAOVg3QgLAKgGAPQgFAPAAAQQAAARAFAQQAGAOALAKQANAJARAAQARAAANgJQALgJAGgPQAGgQgBgRQABgQgGgPQgGgQgLgJQgMgJgSAAQgSAAgMAJgALUBPQgSgMgFgWIAagGQAEAPAKAGQAJAHASAAQASAAALgHQALgJAAgLQAAgJgGgGQgHgHgNgCIgdgIQgYgEgLgMQgLgLAAgTQAAgPAIgLQAJgMAOgGQAOgGATgBQAbAAANAMQAQAMAGASIgZAHQgCgIgEgEQgEgFgIgFQgIgDgLAAQgQAAgLAHQgKAIAAALQAAAJAHAGQAJAHANADIAaAGQAYAGAMAKQALANAAARQAAAPgJAMQgIAMgPAHQgRAHgTAAQgbAAgRgMgAFWBPQgSgLgKgUQgKgVAAgaQAAgZAKgWQAKgUASgMQASgKAYgBQAYABARAKQASAMAKAUQAKAWAAAZQAAAagKAVQgKAUgSALQgRAMgYAAQgYAAgSgMgAFig3QgLAJgGAQQgFAPgBAQQABARAFAQQAGAPALAJQANAJARAAQARAAAMgJQANgKAEgOQAGgQAAgRQAAgQgGgPQgEgPgNgKQgLgJgSAAQgSAAgMAJgABDBPQgTgLgKgTQgKgUAAgcQAAgbAKgTQALgVARgLQASgMAXAAQAOABANAEQANAFALAJQALALAHAQQAGARAAAZIAAAKIh/AAQABARAGANQAHAOAMAHQANAHAQAAQAKAAAJgDQAIgDAHgHQAFgFAEgJIAaAHQgFAOgIAJQgKAJgPAHQgPAFgQAAQgZAAgSgMgABPg4QgLAHgHANQgFAMgBALIBkAAQAAgPgGgLQgGgMgLgHQgLgGgOAAQgRgBgLAJgAjRBQQgRgLgKgUQgJgWAAgbQAAgZAJgVQAKgVARgLQAQgKAWgBQARABAKAFQAKAGAGAHQAGAIACAEIACAAIAAhXIAbAAIAADoIgaAAIAAgaIgDAAIgIALQgIAIgIAGQgLAFgQAAQgVAAgRgLgAjEg3QgLAHgGAQQgFAPAAARQAAARAFARQAGAPALAJQAMAJARAAQAQAAALgIQALgKAFgOQAHgPgBgUQAAgSgFgPQgGgPgLgIQgMgIgPAAQgSgBgLAKgAmYBQQgRgMgJgTQgKgUAAgdQAAgbAKgTQAIgUASgMQAQgKAWgBQARABAKAFQALAGAFAHIAIAMIACAAIAAhXIAbAAIAADoIgaAAIAAgaIgDAAIgIALQgHAIgJAGQgKAFgRAAQgVAAgRgLgAmLg3QgMAIgFAPQgFANAAATQAAATAFAPQAHAQAKAIQAMAJAQAAQARAAALgIQALgJAGgPQAFgOAAgVQAAgUgFgNQgGgPgLgIQgLgIgRAAQgQgBgMAKgAwNBPQgSgLgJgTQgLgWABgaQgBgZALgVQAKgVARgLQATgMAXAAQAOABAMAEQAMAEAMAKQALALAHAQQAGATABAXIAAAKIh/AAQAAARAHANQAGANANAIQAMAHAQAAQALAAAIgDQAKgDAFgHQAHgGADgIIAaAHQgFAOgJAJQgKAJgOAHQgPAFgRAAQgZAAgTgMgAwAg4QgKAHgIANQgFALAAAMIBjAAQAAgPgGgLQgFgMgMgHQgLgGgNAAQgRgBgMAJgAYhBVQgMgFgGgKQgIgLABgPIAAhsIgbAAIAAgXIAbAAIAAgpIAaAAIAAApIAmAAIAAAXIgmAAIAABlQAAALADAGQAEAGAFACQAGACAFgBIAHAAIAFgBIAFAZIgHABIgNABQgMAAgJgEgA07BVQgKgFgIgKQgGgLAAgPIAAhsIgaAAIAAgXIAaAAIAAgpIAbAAIAAApIAlAAIAAAXIglAAIAABlQAAAMACAFQAFAGAEACIALABIAIAAIAFgBIAFAZIgIABIgMABQgMAAgLgEgAfsBXIAAhsQAAgUgLgMQgLgLgSAAQgMAAgLAFQgKAHgGAJQgGAMAAAOIAABoIgbAAIAAiuIAaAAIAAAcIADAAQAGgNAMgJQANgHATgBQASAAANAIQAOAHAIAOQAHAPAAAXIAABtgAcxBXIAAiuIAbAAIAACugAblBXIAAhsQAAgUgLgMQgLgLgSAAQgNAAgMAFQgKAHgGAJQgFALAAAPIAABoIgbAAIAAjoIAbAAIAABWIABAAQAHgNAMgJQAMgHAVgBQASAAANAIQAOAIAHANQAIAPgBAXIAABtgAT1BXIAAhzQAAgUgKgIQgLgIgOAAQgSgBgLALQgKAMAAAQIAABxIgbAAIAAh2QAAgPgKgJQgJgKgQABQgKAAgJAFQgJAHgGAIQgFAKAAANIAABsIgbAAIAAiuIAaAAIAAAcIADAAQAFgNAMgJQALgHASgBQASABALAHQALAIAHAOIACAAQAHgNANgJQANgHATgBQAYAAAPAPQAOAPAAAfIAABzgAIEBXIAAiXIgdAAIAAgXIAdAAIAAgXQAAgOAGgMQAIgJALgGQAMgEALAAQALgBAGACIAJADIgIAYIgFgCIgKgBQgNAAgGAGQgGAIABAMIAAARIAnAAIAAAXIgnAAIAACXgAgmBXIAAjoIAbAAIAADogAoABXIAAiuIAbAAIAACugApLBXIAAhzQAAgUgLgIQgLgIgOAAQgTgBgJALQgKALAAARIAABxIgcAAIAAh2QAAgPgJgJQgKgKgPABQgKAAgKAFQgKAHgFAIQgFAKAAANIAABsIgbAAIAAiuIAaAAIAAAcIADAAQAEgNANgJQAMgHARgBQASABALAHQAMAIAGAOIABAAQAHgNAOgJQANgHATgBQAXAAAPAPQAPAPAAAfIAABzgAx2BXIAAhsQAAgVgLgLQgLgLgSAAQgNAAgLAFQgLAHgGAJQgFALAAAPIAABoIgbAAIAAjoIAbAAIAABWIACAAQAGgNAMgJQAMgHAWgBQAQAAAOAIQAPAHAGAOQAIAPAAAXIAABtgA4FBXIAAhsQAAgUgKgMQgMgLgSAAQgMAAgLAFQgKAHgGAJQgGAMABAOIAABoIgbAAIAAiuIAZAAIAAAcIADAAQAGgNANgJQAMgHATgBQATAAANAIQAOAHAGAOQAIAPAAAXIAABtgA7BBXIAAiuIAbAAIAACugA9mBXIAAhzQAAgUgKgIQgMgIgNAAQgUgBgJALQgLAMAAAQIAABxIgbAAIAAh2QABgOgKgKQgKgKgPABQgKAAgKAFQgJAHgFAIQgFAKgBANIAABsIgbAAIAAiuIAaAAIAAAcIACAAQAGgOAMgIQAMgHASgBQARABAMAHQALAIAHAOIABAAQAHgNANgJQANgHAUgBQAXAAAPAPQAPAPAAAfIAABzgEgjJABXIAAjoIAcAAIAADogEgh5gBAIAAhRIAZAAIAABRgAcxh4QgGgHAAgHQAAgHAGgFQAGgGAHAAQAIAAAGAGQAFAFAAAHQAAAHgFAHQgGAEgIAAQgIAAgFgEgAoAh4QgFgGAAgIQAAgHAFgFQAGgGAIAAQAHAAAGAGQAGAFAAAHQAAAHgGAHQgFAEgIAAQgIAAgGgEgA7Ah4QgGgHAAgHQAAgHAGgFQAFgGAJAAQAHAAAFAGQAHAFAAAHQAAAHgHAHQgFAEgHAAQgJAAgFgEg");
	this.shape.setTransform(-22.45,3.3);

	this.instance = new lib.ClipGroup_1();
	this.instance.setTransform(230,-1.75,1,1,0,0,0,16,16);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#258BF5").s().p("EgmWAFoQg+AAgsgsQgsgrAAg/IAAmjQAAg+AsgsQAsgsA+AAMBMtAAAQA+AAAsAsQAsAsAAA+IAAGjQAAA+gsAsQgsAsg+AAg");
	this.shape_1.setTransform(-2.5,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#258BF5").s().p("AAoBGQg5AAgpgpQgpgoAAg6ICVAAQAAAqACALQAIAyAoAhIAAADg");
	this.shape_2.setTransform(253,29);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.instance},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol50, new cjs.Rectangle(-263,-36,526,72), null);


(lib.Symbol31 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol31, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol30 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol30, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol29 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol29, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol28 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol28, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol27 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol27, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol26 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol26, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol25 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol25, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol24 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol24, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol23 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol23, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol22 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol35();
	this.instance.setTransform(37.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol22, new cjs.Rectangle(-0.3,0,75.7,250), null);


(lib.Symbol21 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(2);
	}
	this.frame_59 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(59).call(this.frame_59).wait(1));

	// Layer_12
	this.instance = new lib.Symbol31();
	this.instance.setTransform(787.5,125,1,1,0,0,0,37.5,125);

	this.instance_1 = new lib.Symbol30();
	this.instance_1.setTransform(112.5,125,1,1,0,0,0,37.5,125);

	this.instance_2 = new lib.Symbol29();
	this.instance_2.setTransform(712.5,125,1,1,0,0,0,37.5,125);

	this.instance_3 = new lib.Symbol28();
	this.instance_3.setTransform(187.5,125,1,1,0,0,0,37.5,125);

	this.instance_4 = new lib.Symbol27();
	this.instance_4.setTransform(637.5,125,1,1,0,0,0,37.5,125);

	this.instance_5 = new lib.Symbol26();
	this.instance_5.setTransform(262.5,125,1,1,0,0,0,37.5,125);

	this.instance_6 = new lib.Symbol25();
	this.instance_6.setTransform(562.5,125,1,1,0,0,0,37.5,125);

	this.instance_7 = new lib.Symbol24();
	this.instance_7.setTransform(337.5,125,1,1,0,0,0,37.5,125);

	this.instance_8 = new lib.Symbol23();
	this.instance_8.setTransform(487.5,125,1,1,0,0,0,37.5,125);

	this.instance_9 = new lib.Symbol22();
	this.instance_9.setTransform(412.5,125,1,1,0,0,0,37.5,125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).to({state:[]},1).wait(59));

	// Symbol_31
	this.instance_10 = new lib.Symbol31();
	this.instance_10.setTransform(787.5,125,1,1,0,0,0,37.5,125);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(1).to({_off:false},0).wait(25).to({y:-125},33,cjs.Ease.quintInOut).wait(1));

	// Symbol_30
	this.instance_11 = new lib.Symbol30();
	this.instance_11.setTransform(112.5,125,1,1,0,0,0,37.5,125);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(1).to({_off:false},0).wait(24).to({y:375},33,cjs.Ease.quintInOut).wait(2));

	// Symbol_29
	this.instance_12 = new lib.Symbol29();
	this.instance_12.setTransform(712.5,125,1,1,0,0,0,37.5,125);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(1).to({_off:false},0).wait(23).to({y:375},33,cjs.Ease.quintInOut).wait(3));

	// Symbol_28
	this.instance_13 = new lib.Symbol28();
	this.instance_13.setTransform(187.5,125,1,1,0,0,0,37.5,125);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(1).to({_off:false},0).wait(22).to({y:-125},33,cjs.Ease.quintInOut).wait(4));

	// Symbol_27
	this.instance_14 = new lib.Symbol27();
	this.instance_14.setTransform(637.5,125,1,1,0,0,0,37.5,125);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(1).to({_off:false},0).wait(21).to({y:-125},33,cjs.Ease.quintInOut).wait(5));

	// Symbol_26
	this.instance_15 = new lib.Symbol26();
	this.instance_15.setTransform(262.5,125,1,1,0,0,0,37.5,125);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(1).to({_off:false},0).wait(20).to({y:375},33,cjs.Ease.quintInOut).wait(6));

	// Symbol_25
	this.instance_16 = new lib.Symbol25();
	this.instance_16.setTransform(562.5,125,1,1,0,0,0,37.5,125);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(1).to({_off:false},0).wait(19).to({y:375},33,cjs.Ease.quintInOut).wait(7));

	// Symbol_24
	this.instance_17 = new lib.Symbol24();
	this.instance_17.setTransform(337.5,125,1,1,0,0,0,37.5,125);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(1).to({_off:false},0).wait(18).to({y:-125},33,cjs.Ease.quintInOut).wait(8));

	// Symbol_23
	this.instance_18 = new lib.Symbol23();
	this.instance_18.setTransform(487.5,125,1,1,0,0,0,37.5,125);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(1).to({_off:false},0).wait(17).to({y:-125},33,cjs.Ease.quintInOut).wait(9));

	// Symbol_22
	this.instance_19 = new lib.Symbol22();
	this.instance_19.setTransform(412.5,125,1,1,0,0,0,37.5,125);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(1).to({_off:false},0).wait(16).to({y:375},33,cjs.Ease.quintInOut).wait(10));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(74.7,-250,750.6999999999999,750);


(lib.Symbol10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(2);
	}
	this.frame_99 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(99).call(this.frame_99).wait(1));

	// Layer_9
	this.instance = new lib.Symbol58();
	this.instance.setTransform(311.85,88.3);

	this.instance_1 = new lib.Symbol57();
	this.instance_1.setTransform(140.4,93.55);

	this.instance_2 = new lib.Symbol56();
	this.instance_2.setTransform(435.1,26.2);

	this.instance_3 = new lib.Symbol55();
	this.instance_3.setTransform(242.6,26.3);

	this.instance_4 = new lib.Symbol52();
	this.instance_4.setTransform(299.05,30.25);

	this.instance_5 = new lib.Symbol54();
	this.instance_5.setTransform(77.6,26.2);

	this.instance_6 = new lib.Symbol53();
	this.instance_6.setTransform(-13.2,26.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).to({state:[]},1).wait(99));

	// Symbol_18
	this.instance_7 = new lib.Symbol58();
	this.instance_7.setTransform(311.85,130.3);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(54).to({_off:false},0).to({y:88.3,alpha:1},18,cjs.Ease.quintInOut).wait(28));

	// Symbol_17
	this.instance_8 = new lib.Symbol57();
	this.instance_8.setTransform(140.4,135.55);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(51).to({_off:false},0).to({y:93.55,alpha:1},18,cjs.Ease.quintInOut).wait(31));

	// Symbol_15
	this.instance_9 = new lib.Symbol56();
	this.instance_9.setTransform(435.1,54.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(29).to({_off:false},0).to({y:26.2,alpha:1},18,cjs.Ease.quintInOut).wait(53));

	// Symbol_14
	this.instance_10 = new lib.Symbol55();
	this.instance_10.setTransform(242.6,54.3);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(26).to({_off:false},0).to({y:26.3,alpha:1},18,cjs.Ease.quintInOut).wait(56));

	// Layer_11
	this.instance_11 = new lib.Symbol52();
	this.instance_11.setTransform(253.25,30.25,0.0771,1);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(79).to({_off:false},0).to({scaleX:1,x:299.05,alpha:1},20,cjs.Ease.quintInOut).wait(1));

	// Symbol_13
	this.instance_12 = new lib.Symbol54();
	this.instance_12.setTransform(77.6,54.2);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(4).to({_off:false},0).to({y:26.2,alpha:1},18,cjs.Ease.quintInOut).wait(78));

	// Symbol_12
	this.instance_13 = new lib.Symbol53();
	this.instance_13.setTransform(-13.2,54.7);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(1).to({_off:false},0).to({y:26.7,alpha:1},18,cjs.Ease.quintInOut).wait(81));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.5,7.2,551.5,141.10000000000002);


(lib.emoji = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(2);
	}
	this.frame_9 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(9).call(this.frame_9).wait(1));

	// Layer_2
	this.instance = new lib.Symbol9();
	this.instance.setTransform(80,80,1,1,0,0,0,80,80);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(9));

	// Layer_1
	this.instance_1 = new lib.Symbol9();
	this.instance_1.setTransform(80.05,80.05,1.3394,1.3394,0,0,0,80,80);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({scaleX:1,scaleY:1,x:80,y:80,alpha:1},8,cjs.Ease.backOut).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.1,-27.1,214.29999999999998,214.29999999999998);


(lib.button18 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer 1
	this.instance = new lib.shape17Hit("synched",0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-901.6,-96.3,1803.3000000000002,192.6);


(lib.Symbol8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(2);
	}
	this.frame_109 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(109).call(this.frame_109).wait(1));

	// Layer_28
	this.instance = new lib.emoji();
	this.instance.setTransform(319,18.5,1,1,0,0,0,80,80);

	this.instance_1 = new lib.emoji();
	this.instance_1.setTransform(313,-79.5,1,1,0,0,0,80,80);

	this.instance_2 = new lib.emoji();
	this.instance_2.setTransform(73,-109.65,1,1,0,0,0,80,80);

	this.instance_3 = new lib.emoji();
	this.instance_3.setTransform(103,88.5,1,1,0,0,0,80,80);

	this.instance_4 = new lib.emoji();
	this.instance_4.setTransform(105,-18.5,1,1,0,0,0,80,80);

	this.instance_5 = new lib.emoji();
	this.instance_5.setTransform(-105,-98.5,1,1,0,0,0,80,80);

	this.instance_6 = new lib.emoji();
	this.instance_6.setTransform(-238,-90.5,1,1,0,0,0,80,80);

	this.instance_7 = new lib.emoji();
	this.instance_7.setTransform(-217,-65.5,1,1,0,0,0,80,80);

	this.instance_8 = new lib.emoji();
	this.instance_8.setTransform(-185,-35.5,1,1,0,0,0,80,80);

	this.instance_9 = new lib.emoji();
	this.instance_9.setTransform(-185,14.5,1,1,0,0,0,80,80);

	this.instance_10 = new lib.emoji();
	this.instance_10.setTransform(-351,18.5,1,1,0,0,0,80,80);

	this.instance_11 = new lib.emoji();
	this.instance_11.setTransform(-251,69.5,1,1,0,0,0,80,80);

	this.instance_12 = new lib.emoji();
	this.instance_12.setTransform(233,98.5,1,1,0,0,0,80,80);

	this.instance_13 = new lib.emoji();
	this.instance_13.setTransform(-40,-65.5,1,1,0,0,0,80,80);

	this.instance_14 = new lib.emoji();
	this.instance_14.setTransform(351,94.5,1,1,0,0,0,80,80);

	this.instance_15 = new lib.emoji();
	this.instance_15.setTransform(-288,-10.5,1,1,0,0,0,80,80);

	this.instance_16 = new lib.emoji();
	this.instance_16.setTransform(-57,80.5,1,1,0,0,0,80,80);

	this.instance_17 = new lib.emoji();
	this.instance_17.setTransform(200,-90.5,1,1,0,0,0,80,80);

	this.instance_18 = new lib.emoji();
	this.instance_18.setTransform(-351,88.5,1,1,0,0,0,80,80);

	this.instance_19 = new lib.emoji();
	this.instance_19.setTransform(212,8.5,1,1,0,0,0,80,80);

	this.instance_20 = new lib.emoji();
	this.instance_20.setTransform(-159.85,85.5,1,1,0,0,0,80,80);

	this.instance_21 = new lib.emoji();
	this.instance_21.setTransform(-345,-79.5,1,1,0,0,0,80,80);

	this.instance_22 = new lib.emoji();
	this.instance_22.setTransform(23,61.5,1,1,0,0,0,80,80);

	this.instance_23 = new lib.emoji();
	this.instance_23.setTransform(61,-53.5,1,1,0,0,0,80,80);

	this.instance_24 = new lib.emoji();
	this.instance_24.setTransform(-78,14.5,1,1,0,0,0,80,80);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_24},{t:this.instance_23},{t:this.instance_22},{t:this.instance_21},{t:this.instance_20},{t:this.instance_19},{t:this.instance_18},{t:this.instance_17},{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).to({state:[]},1).wait(109));

	// _Clip_Group__3_0
	this.instance_25 = new lib.emoji();
	this.instance_25.setTransform(319,18.5,1,1,0,0,0,80,80);
	this.instance_25._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_25).wait(47).to({_off:false},0).wait(22).to({y:-200.2},15,cjs.Ease.backIn).wait(26));

	// _Clip_Group__4_0
	this.instance_26 = new lib.emoji();
	this.instance_26.setTransform(313,-79.5,1,1,0,0,0,80,80);
	this.instance_26._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_26).wait(51).to({_off:false},0).wait(19).to({y:-200.2},15,cjs.Ease.backIn).wait(25));

	// _Clip_Group__6
	this.instance_27 = new lib.emoji();
	this.instance_27.setTransform(73,-109.65,1,1,0,0,0,80,80);
	this.instance_27._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_27).wait(49).to({_off:false},0).wait(22).to({y:-200.2},15,cjs.Ease.backIn).wait(24));

	// _Clip_Group__9
	this.instance_28 = new lib.emoji();
	this.instance_28.setTransform(103,88.5,1,1,0,0,0,80,80);
	this.instance_28._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_28).wait(48).to({_off:false},0).wait(24).to({y:-200.2},15,cjs.Ease.backIn).wait(23));

	// _Clip_Group__10
	this.instance_29 = new lib.emoji();
	this.instance_29.setTransform(105,-18.5,1,1,0,0,0,80,80);
	this.instance_29._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_29).wait(50).to({_off:false},0).wait(23).to({y:-200.2},15,cjs.Ease.backIn).wait(22));

	// _Clip_Group__11
	this.instance_30 = new lib.emoji();
	this.instance_30.setTransform(-105,-98.5,1,1,0,0,0,80,80);
	this.instance_30._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_30).wait(44).to({_off:false},0).wait(30).to({y:-200.2},15,cjs.Ease.backIn).wait(21));

	// _Clip_Group__15
	this.instance_31 = new lib.emoji();
	this.instance_31.setTransform(-238,-90.5,1,1,0,0,0,80,80);
	this.instance_31._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_31).wait(45).to({_off:false},0).wait(30).to({y:-200.2},15,cjs.Ease.backIn).wait(20));

	// _Clip_Group__16
	this.instance_32 = new lib.emoji();
	this.instance_32.setTransform(-217,-65.5,1,1,0,0,0,80,80);
	this.instance_32._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_32).wait(46).to({_off:false},0).wait(30).to({y:-200.2},15,cjs.Ease.backIn).wait(19));

	// _Clip_Group__17
	this.instance_33 = new lib.emoji();
	this.instance_33.setTransform(-185,-35.5,1,1,0,0,0,80,80);
	this.instance_33._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_33).wait(42).to({_off:false},0).wait(35).to({y:-200.2},15,cjs.Ease.backIn).wait(18));

	// _Clip_Group__18
	this.instance_34 = new lib.emoji();
	this.instance_34.setTransform(-185,14.5,1,1,0,0,0,80,80);
	this.instance_34._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_34).wait(40).to({_off:false},0).wait(38).to({y:-200.2},15,cjs.Ease.backIn).wait(17));

	// _Clip_Group__22
	this.instance_35 = new lib.emoji();
	this.instance_35.setTransform(-351,18.5,1,1,0,0,0,80,80);
	this.instance_35._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_35).wait(41).to({_off:false},0).wait(38).to({y:-200.2},15,cjs.Ease.backIn).wait(16));

	// _Clip_Group__20
	this.instance_36 = new lib.emoji();
	this.instance_36.setTransform(-251,69.5,1,1,0,0,0,80,80);
	this.instance_36._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_36).wait(38).to({_off:false},0).wait(42).to({y:-200.2},15,cjs.Ease.backIn).wait(15));

	// _Clip_Group__1_0
	this.instance_37 = new lib.emoji();
	this.instance_37.setTransform(233,98.5,1,1,0,0,0,80,80);
	this.instance_37._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_37).wait(37).to({_off:false},0).wait(44).to({y:-200.2},15,cjs.Ease.backIn).wait(14));

	// _Clip_Group__14
	this.instance_38 = new lib.emoji();
	this.instance_38.setTransform(-40,-65.5,1,1,0,0,0,80,80);
	this.instance_38._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_38).wait(36).to({_off:false},0).wait(46).to({y:-200.2},15,cjs.Ease.backIn).wait(13));

	// _Clip_Group__2_0
	this.instance_39 = new lib.emoji();
	this.instance_39.setTransform(351,94.5,1,1,0,0,0,80,80);
	this.instance_39._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_39).wait(35).to({_off:false},0).wait(48).to({y:-200.2},15,cjs.Ease.backIn).wait(12));

	// _Clip_Group__23
	this.instance_40 = new lib.emoji();
	this.instance_40.setTransform(-288,-10.5,1,1,0,0,0,80,80);
	this.instance_40._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_40).wait(34).to({_off:false},0).wait(50).to({y:-200.2},15,cjs.Ease.backIn).wait(11));

	// _Clip_Group__13
	this.instance_41 = new lib.emoji();
	this.instance_41.setTransform(-57,80.5,1,1,0,0,0,80,80);
	this.instance_41._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_41).wait(33).to({_off:false},0).wait(52).to({y:-200.2},15,cjs.Ease.backIn).wait(10));

	// _Clip_Group__5_0
	this.instance_42 = new lib.emoji();
	this.instance_42.setTransform(200,-90.5,1,1,0,0,0,80,80);
	this.instance_42._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_42).wait(32).to({_off:false},0).wait(54).to({y:-200.2},15,cjs.Ease.backIn).wait(9));

	// _Clip_Group__21
	this.instance_43 = new lib.emoji();
	this.instance_43.setTransform(-351,88.5,1,1,0,0,0,80,80);
	this.instance_43._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_43).wait(31).to({_off:false},0).wait(56).to({y:-200.2},15,cjs.Ease.backIn).wait(8));

	// _Clip_Group__25
	this.instance_44 = new lib.emoji();
	this.instance_44.setTransform(212,8.5,1,1,0,0,0,80,80);
	this.instance_44._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_44).wait(30).to({_off:false},0).wait(58).to({y:-200.2},15,cjs.Ease.backIn).wait(7));

	// _Clip_Group__19
	this.instance_45 = new lib.emoji();
	this.instance_45.setTransform(-159.85,85.5,1,1,0,0,0,80,80);
	this.instance_45._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_45).wait(29).to({_off:false},0).wait(60).to({y:-200.2},15,cjs.Ease.backIn).wait(6));

	// _Clip_Group__24
	this.instance_46 = new lib.emoji();
	this.instance_46.setTransform(-345,-79.5,1,1,0,0,0,80,80);
	this.instance_46._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_46).wait(28).to({_off:false},0).wait(62).to({y:-200.2},15,cjs.Ease.backIn).wait(5));

	// _Clip_Group__8
	this.instance_47 = new lib.emoji();
	this.instance_47.setTransform(23,61.5,1,1,0,0,0,80,80);
	this.instance_47._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_47).wait(19).to({_off:false},0).wait(72).to({y:-200.2},15,cjs.Ease.backIn).wait(4));

	// _Clip_Group__7
	this.instance_48 = new lib.emoji();
	this.instance_48.setTransform(61,-53.5,1,1,0,0,0,80,80);
	this.instance_48._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_48).wait(10).to({_off:false},0).wait(82).to({y:-200.2},15,cjs.Ease.backIn).wait(3));

	// _Clip_Group__12
	this.instance_49 = new lib.emoji();
	this.instance_49.setTransform(-78,14.5,1,1,0,0,0,80,80);
	this.instance_49._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_49).wait(1).to({_off:false},0).wait(92).to({y:-200.2},15,cjs.Ease.backIn).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-431,-280.2,862,488.4);


// stage content:
(lib.gatewise_300x100_v3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,729];
	// timeline functions:
	this.frame_0 = function() {
		this.btn1.addEventListener("click", fl_ClickToGoToWebPage_2);
		
		function fl_ClickToGoToWebPage_2() {
			window.open(clickTag, "_blank");
		}
	}
	this.frame_729 = function() {
		/*this.stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(729).call(this.frame_729).wait(1));

	// button
	this.btn1 = new lib.button18();
	this.btn1.name = "btn1";
	this.btn1.setTransform(150.65,51.65,0.1663,0.5191,0,0,0,4.8,3.5);
	new cjs.ButtonHelper(this.btn1, 0, 1, 2, false, new lib.button18(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn1).wait(730));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(0.5,1,1).p("A3ZnxMAuzAAAIAAPjMguzAAAg");
	this.shape.setTransform(150,50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(730));

	// Layer_1
	this.instance = new lib.Symbol8();
	this.instance.setTransform(158.2,49.8,0.3999,0.3999,0,0,0,0.4,0.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(299).to({_off:false},0).to({_off:true},111).wait(320));

	// Layer_13
	this.instance_1 = new lib.Symbol10();
	this.instance_1.setTransform(150.05,51.3,0.4595,0.4595,0,0,0,233.1,59.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(400).to({_off:false},0).to({regX:233.2,regY:59.5,scaleX:0.3999,scaleY:0.3999,x:150,y:51.05},154).to({regX:234.3,regY:60.5,scaleX:0.0992,scaleY:0.0992,y:50.35,alpha:0},15,cjs.Ease.backIn).to({_off:true},1).wait(160));

	// Layer_10
	this.instance_2 = new lib.Symbol20();
	this.instance_2.setTransform(150,50,0.3999,0.3999,0,0,0,375.1,125);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(374).to({_off:false},0).wait(180).to({alpha:0},15).to({_off:true},1).wait(160));

	// Layer_14
	this.instance_3 = new lib.Symbol21();
	this.instance_3.setTransform(150,50,0.3999,0.3999,0,0,0,449.7,125);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(554).to({_off:false},0).to({_off:true},46).wait(130));

	// Layer_18
	this.instance_4 = new lib.Symbol48();
	this.instance_4.setTransform(151.6,74.85,0.4,0.4,0,0,0,0.2,0.2);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(634).to({_off:false},0).to({alpha:1},20).wait(65).to({regX:0.4,scaleX:0.3648,scaleY:0.3648,x:151.65,y:72.85,alpha:0},10,cjs.Ease.quadIn).wait(1));

	// Layer_16
	this.instance_5 = new lib.Symbol33();
	this.instance_5.setTransform(150.05,80.4,0.3999,0.3999,0,0,0,273.8,39.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(589).to({_off:false},0).to({y:39.4,alpha:1},25,cjs.Ease.backOut).wait(105).to({regX:274,scaleX:0.3648,scaleY:0.3648,x:150.25,y:40.55,alpha:0},10,cjs.Ease.quadIn).wait(1));

	// Symbol_6
	this.instance_6 = new lib.Symbol51();
	this.instance_6.setTransform(280.4,91,0.2372,0.2372,0,0,0,232.1,60.3);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(181).to({_off:false},0).to({regX:232.2,regY:60,scaleX:0.4,scaleY:0.4,x:280.45,y:91.3,alpha:1},19,cjs.Ease.backOut).to({_off:true},154).wait(376));

	// Symbol_5
	this.instance_7 = new lib.Symbol50();
	this.instance_7.setTransform(280.4,91.3,0.2578,0.2578,0,0,0,263.1,36.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(105).to({_off:false},0).to({scaleX:0.4,scaleY:0.4,alpha:1},20,cjs.Ease.backOut).wait(54).to({y:37.9},20,cjs.Ease.backOut).to({_off:true},155).wait(376));

	// Symbol_1
	this.instance_8 = new lib.Symbol49();
	this.instance_8.setTransform(19.6,74,0.2366,0.2366,0,0,0,-232.8,60.2);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(4).to({_off:false},0).to({regX:-232.9,regY:60.1,scaleX:0.4,scaleY:0.4,alpha:1},20,cjs.Ease.backOut).wait(80).to({y:57.05},20,cjs.Ease.backOut).wait(55).to({regY:60,y:-0.5},20,cjs.Ease.backOut).to({_off:true},155).wait(376));

	// Layer_2
	this.instance_9 = new lib.Symbol4();
	this.instance_9.setTransform(150.1,50.1,0.3999,0.3999,0,0,0,0.4,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(730));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(135.7,-4.2,194.7,125.2);
// library properties:
lib.properties = {
	id: 'DBCB6AE561EBE8498EC65EA2F73D3964',
	width: 300,
	height: 100,
	fps: 45,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/gatewise_300x100_v3_atlas_1.png", id:"gatewise_300x100_v3_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['DBCB6AE561EBE8498EC65EA2F73D3964'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;